var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__32f657b8._.js")
R.c("server/chunks/ssr/d3e3e_next_dist_59034563._.js")
R.c("server/chunks/ssr/d3e3e_next_dist_98ed6b61._.js")
R.c("server/chunks/ssr/[root-of-the-server]__db4a60f7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f3b39e2a._.js")
R.c("server/chunks/ssr/d3e3e_next_dist_e19cd2e2._.js")
R.c("server/chunks/ssr/_next-internal_server_app__global-error_page_actions_75761787.js")
R.m(24246)
module.exports=R.m(24246).exports
